apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: salim2brahem/flask-app
        name: flask-app
        env:
          - name: DB_HOST
            value: "mysql-service"
          - name: DB_USER
            value: "demo"
          - name: DB_PASSWORD
            value: "demo"
          - name: DB_NAME
            value: "phishing_database"
        resources: {}
status: {}
