apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app
  name: flask-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 5000
    nodePort: 30002
  selector:
    app: flask-app
  type: NodePort
status:
  loadBalancer: {}
