apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front-service
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: front
  type: NodePort
status:
  loadBalancer: {}
