apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "demo"
            - name: MYSQL_DATABASE
              value: "phishing_database"
            - name: MYSQL_USER
              value: "demo"
            - name: MYSQL_PASSWORD
              value: "demo"
